typography_spectrum: 0.17824282384744966
color:
  brandStrength: 0.2662271855992846
  lightness: 0.26931351327586295
  saturation: 0.9172696290490688
  rhythmicContrast: 0.7003814514528148
  brandColors:
    - '#304269'
    - '#91BED4'
    - '#D9E8F5'
    - '#FFFFFF'
    - '#F26101'
layout_spectrum: 0.16602641008277932
author:
  name: Powered by Mobywise
  email: info@mobywise.com
  url: 'http://mobywise.com'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dcbf9218-61f0-4660-9ae7-701355d58f57.png
name: ' '
url: 'http://cognactiva.com/'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Servicios
    id: e61b20fb-e511-46b5-bc24-20d2b9c5de32
    type: content
  - name: Cursos
    id: 3e6c2291-ef44-4697-a49e-0a241ff4345f
    type: content
  - name: CgA Plus
    url: 'https://www.youtube.com/channel/UCiVOVtebXHujHvLlmhvnvgQ'
    type: external
  - name: Ayuda & KB
    url: 'http://cognactiva.helpscoutdocs.com'
    type: external
  - name: Autismo 360
    url: 'https://www.facebook.com/Autismo-360-785179814992348/'
    type: external
  - name: Quienes somos
    id: 658e1661-1299-4762-9f9b-1c2ca7d377dc
    type: content
  - name: Contáctenos
    id: 514dd4a5-1cdb-4012-bfff-6f1dcfae88c5
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c9c86774-3a4e-46f9-9e23-bfb449c2f7b3.png
title: CognActiva
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fwww.youtube.com%2Fembed%2FD0fUy7UXD-g%3Ffeature%3Doembed&url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DD0fUy7UXD-g&image=https%3A%2F%2Fi.ytimg.com%2Fvi%2FD0fUy7UXD-g%2Fhqdefault.jpg&key=b7d04c9b404c499eba89ee7072e1c4f7&type=text%2Fhtml&schema=youtube"
      width="640" height="360" scrolling="no" frameborder="0"
      allowfullscreen></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      datePublished: null
      isBasedOnUrl: 'https://youtu.be/D0fUy7UXD-g'
      keywords:
        - cognactiva
        - tecnolog
        - activaci
        - cognitiva
        - personalizada
        - '227'
        - spicer
        - available
        - maher
        - snl
      related: []
      author:
        - name: CognActiva Plus
          url: 'https://www.youtube.com/channel/UCiVOVtebXHujHvLlmhvnvgQ'
          avatar: {}
      '@context': 'http://schema.org'
      title: Reel 00 - CgA+ Portada
      '@type': VideoObject
      app_links:
        - url: 'vnd.youtube://www.youtube.com/watch?v=D0fUy7UXD-g&feature=applinks'
          type: ios
          namespace: ai
          app_store_id: '544007664'
          app_name: YouTube
        - url: 'vnd.youtube://www.youtube.com/watch?v=D0fUy7UXD-g&feature=applinks'
          type: android
          namespace: ai
          app_name: YouTube
          package: com.google.android.youtube
        - url: 'https://www.youtube.com/watch?v=D0fUy7UXD-g&feature=applinks'
          type: web
          namespace: ai
        - url: 'vnd.youtube://www.youtube.com/watch?v=D0fUy7UXD-g&feature=applinks'
          namespace: twitter
          type: ipad
          name: YouTube
          id: '544007664'
        - url: 'vnd.youtube://www.youtube.com/watch?v=D0fUy7UXD-g&feature=applinks'
          namespace: twitter
          type: iphone
          name: YouTube
          id: '544007664'
        - url: 'https://www.youtube.com/watch?v=D0fUy7UXD-g'
          namespace: twitter
          type: googleplay
          name: YouTube
          id: com.google.android.youtube
        - path: http/www.youtube.com/watch?v=D0fUy7UXD-g
          package: com.google.android.youtube
          namespace: google
          type: android
        - path: vnd.youtube/www.youtube.com/watch?v=D0fUy7UXD-g
          package: '544007664'
          namespace: google
          type: ios
      publisher:
        url: 'https://www.youtube.com/'
        name: YouTube
        favicon: 'https://s.ytimg.com/yts/img/favicon-vflz7uhzw.ico'
        domain: youtu.be
      description: CognActiva - Tecnología para la activación cognitiva personalizada
      inLanguage: en
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Tecnología para la Activación Cognitiva Personalizada
purpose:
  - type: internal
    label: Cognactívese
    item: 77ca54ba-549a-46a6-922b-d469e72ba9bd
  - type: internal
    label: Contáctenos ahora
    item: 514dd4a5-1cdb-4012-bfff-6f1dcfae88c5
github: true
content_rating:
  adult: false
